# 이름 : application-local.yml
# 로컬 환경에서 사용할 설정 파일
# redis와 mysql 로컬 환경에서 사용할 설정
# 기본적으로 DB는 localhost에 연결
spring:
    datasource:
        url: jdbc:mysql://localhost:3307/packet_db?serverTimezone=UTC&characterEncoding=UTF-8
        username: admin
        password: admin
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
                show_sql: true

    data:
        redis:
            host: localhost
            port: 6379
            password: 1234

swagger:
    base-url: http://localhost:8080